# only trigger build through main or release branch
trigger:
- main
- release/*

name: $(Build.SourceBranch).$(Date:yy)$(DayOfYear)$(Rev:.r) 

variables:
  vmImage: 'ubuntu-latest'
  projectName: 'Southport.Messaging.Email.MailGun'
  buildConfiguration: 'Release'

stages:
#------------------------Build Library - Main------------------------------------------
- stage: 'BuildLibraryMain'
  displayName: 'Build - Library'
  dependsOn: []
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
    artifactName: 'dev-library'
  jobs:
  - template: 'DevOps/build.yml'

#------------------------Build Library - Release------------------------------------------
- stage: 'BuildLibraryRelease'
  displayName: 'Build - Library'
  dependsOn: []
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
  variables:
    artifactName: 'release-library'
  jobs:
  - template: 'DevOps/build.yml'

#------------------------Deploy LIBRARY------------------------------------------
- stage: 'PublishLibraryRelease'
  displayName: 'Deploy to prod (release)'
  dependsOn: 'BuildLibraryRelease'
  condition: succeeded()
  variables:
    environment: 'nuget-publish-approval'
    artifact: 'release-library'
  jobs:
  - template: 'DevOps/deploy.yml'
